# Generated by Django 3.1.2 on 2021-05-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_teacher_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='school.Teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='school.Student'),
        ),
    ]
